In [1]:
import syft as sy
import numpy as np

In [2]:
domain = sy.login(email="info@openmined.org", password="changethis", port=8081)


Anyone can login as an admin to your node right now because your password is still the default PySyft username and password!!!

Connecting to localhost... done! 	 Logging into canada... done!


In [3]:
domain.datasets.purge(skip_check=True)

In [4]:
if len(domain.datasets) == 0:
    data = np.random.random((5, 5))
    gt_dsa = np.random.choice(["Bob", "Billy", "Brandon"], (5, 5))
    pt_dsa = np.random.choice(["Joe"], (5, 5))
    gamma_tensor = sy.Tensor(data).private(min_val=0, max_val=1, data_subjects=gt_dsa)
    phi_tensor = sy.Tensor(data).private(min_val=0, max_val=1, data_subjects=pt_dsa)

    domain.load_dataset(
        assets={
            "phi": phi_tensor, 
            "gamma": gamma_tensor
        }, 
        name="Test dataset", 
        description="Descr."
    )
else:
    domain.datasets

Loading dataset... uploading...🚀                                                                                                                                             

Uploading `gamma`: 100%|█████████████████████████████████████████████| 1/1 [00:00<00:00, 139.32it/s]

Dataset is uploaded successfully !!! 🎉

Run `<your client variable>.datasets` to see your new dataset loaded into your machine!


In [5]:
phi = domain.datasets[-1]["phi"]

In [6]:
data = phi.get_copy().child

In [7]:
data//data

/Users/rasswanth/PySyft/packages/syft/src/syft/core/tensor/autodp/phi_tensor.py:2871: RuntimeWarning: divide by zero encountered in floor_divide
  min_min = self.min_vals.data // other.min_vals.data
/Users/rasswanth/PySyft/packages/syft/src/syft/core/tensor/autodp/phi_tensor.py:2873: RuntimeWarning: divide by zero encountered in floor_divide
  max_min = self.max_vals.data // other.min_vals.data


PhiTensor(child=[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]], min_vals=<lazyrepeatarray data: [0] -> shape: (5, 5)>, max_vals=<lazyrepeatarray data: [1] -> shape: (5, 5)>)

In [8]:
res = phi//phi

/Users/rasswanth/PySyft/packages/syft/src/syft/core/tensor/lazy_repeat_array.py:212: RuntimeWarning: divide by zero encountered in floor_divide
  return self.__class__(data=self.data // other.data, shape=self.shape)


In [9]:
res.get_copy()

Tensor(child=PhiTensor(child=[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]], min_vals=<lazyrepeatarray data: [0] -> shape: (5, 5)>, max_vals=<lazyrepeatarray data: [1] -> shape: (5, 5)>))

In [10]:
phi.get_copy()

Tensor(child=PhiTensor(child=[[0.06468493 0.14997954 0.20649089 0.22461705 0.84255737]
 [0.64469158 0.84759673 0.57895809 0.87734141 0.52062476]
 [0.08955554 0.63137593 0.16988962 0.95861889 0.10079708]
 [0.21855769 0.60517886 0.68151371 0.13608255 0.44989138]
 [0.36328337 0.59083746 0.93861341 0.36223995 0.96805267]], min_vals=<lazyrepeatarray data: [0] -> shape: (5, 5)>, max_vals=<lazyrepeatarray data: [1] -> shape: (5, 5)>))

In [ ]:
phi_res = phi.get_copy()
print(phi_res.child.child, phi_res.child.data_subjects.sum(), phi_res.child.min_vals, phi_res.child.max_vals)

In [11]:
gamma = domain.datasets[-1]["gamma"]

In [12]:
data = gamma.get_copy().child

In [13]:
local_res = data//data
print(local_res.child)
print(local_res.min_vals)
print(local_res.max_vals)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
<lazyrepeatarray data: [0] -> shape: (5, 5)>
<lazyrepeatarray data: [1] -> shape: (5, 5)>


/Users/rasswanth/PySyft/packages/syft/src/syft/core/tensor/autodp/gamma_tensor.py:3083: RuntimeWarning: divide by zero encountered in floor_divide
  min_min = self.min_vals.data // other.min_vals.data
/Users/rasswanth/PySyft/packages/syft/src/syft/core/tensor/autodp/gamma_tensor.py:3085: RuntimeWarning: divide by zero encountered in floor_divide
  max_min = self.max_vals.data // other.min_vals.data


In [14]:
res = gamma//gamma

In [15]:
final_res = res.get_copy().child
print(final_res.child)
print(final_res.min_vals)
print(final_res.max_vals)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
<lazyrepeatarray data: [0] -> shape: (5, 5)>
<lazyrepeatarray data: [1] -> shape: (5, 5)>


In [ ]:
data.data_subjects **2

In [ ]:
np.arange(6)